{% set name = "logdir" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logdir-{{ version }}.tar.gz
  sha256: d0c4897f4e65c40be03ab484db1d545ea5df918a558904a5a515eb19204e520b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry
  run:
    - dulwich >=0.20.0
    - python >=3.7,<4.0
    - ruamel.yaml >0.15
    - toml >=0.10

test:
  imports:
    - logdir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://logdir.btjanka.net
  summary: A utility for managing logging directories.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - btjanaka
