{% set name = "logdir" %}
{% set version = "0.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logdir-{{ version }}.tar.gz
  sha256: b4d08e4b481f19bb043a8cfba6bdc3ad6e3c2612a4343b060d9cdf7279177122

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry
  run:
    - dulwich >=0.20.0
    - python >=3.7,<4.0
    - ruamel.yaml >0.15
    - toml >=0.10

test:
  imports:
    - logdir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://logdir.btjanka.net
  summary: A utility for managing logging directories.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - btjanaka
